[[constraint]]
  name = "k8s.io/api"
  branch = "release-1.9"

[[constraint]]
  name = "k8s.io/apiextensions-apiserver"
  branch = "release-1.9"  


[[constraint]]
  name = "k8s.io/apimachinery"
  branch = "release-1.9"    

[[constraint]]
  name = "k8s.io/client-go"
  version = "~6.0"

[[constraint]]
  name = "github.com/coreos/etcd"
  version = "=3.1.9"

[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "=v1.13.8"

[[constraint]]
  name = "github.com/pborman/uuid"
  version = "=v1.1"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "=v0.8.0"

[[constraint]]
  name = "github.com/prometheus/client_golang"
  version = "=v0.8.0"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "=v1.0.4"

[[constraint]]
  name = "golang.org/x/time"

[[constraint]]
  name = "github.com/Azure/azure-sdk-for-go"
  version = "=v11.3.0-beta"
